# Generated by Django 6.0.1 on 2026-08-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0016_alter_walletpreferences_id_alter_walletprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpreferences',
            name='nft_image_uri_template',
            field=models.CharField(default='ipfs://{cid}/{filename}', help_text='Template for generated NFT image URIs. Use {cid} and {filename}.', max_length=255),
        ),
    ]
