# Generated by Django 6.0.1 on 2026-08-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_contractinteraction_user'),
        ('DeFi', '0008_swapoffer_settlement_temp_txid_swapfundinglock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChannelPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_key', models.CharField(max_length=64)),
                ('channel_name', models.CharField(max_length=255)),
                ('network_mode', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='testnet', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=12)),
                ('schema_name', models.CharField(default='defitome.atomic-swap-transfer-message', max_length=120)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('allowed_stages', models.JSONField(default=list)),
                ('strict_rules', models.JSONField(default=dict)),
                ('rules_checksum', models.CharField(blank=True, max_length=64)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_message_channel_policies', to=settings.AUTH_USER_MODEL)),
                ('owner_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_message_channel_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('channel_key', '-version'),
            },
        ),
        migrations.CreateModel(
            name='AtomicSwapTransferMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('payload_checksum', models.CharField(max_length=64)),
                ('payload_ipfs_cid', models.CharField(blank=True, max_length=255)),
                ('broadcast_result', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('broadcasted', 'Broadcasted'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='recorded', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('swap_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_messages', to='DeFi.swapoffer')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='API.messagechannelpolicy')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='messagechannelpolicy',
            index=models.Index(fields=['channel_key', 'network_mode', 'status'], name='API_message_channel_fd497b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagechannelpolicy',
            index=models.Index(fields=['owner_account', 'network_mode'], name='API_message_owner_a_226715_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagechannelpolicy',
            constraint=models.UniqueConstraint(fields=('channel_key', 'network_mode', 'version'), name='message_channel_policy_key_network_version_unique'),
        ),
        migrations.AddIndex(
            model_name='atomicswaptransfermessage',
            index=models.Index(fields=['swap_offer', 'stage', '-created_at'], name='API_atomics_swap_of_eca14d_idx'),
        ),
        migrations.AddIndex(
            model_name='atomicswaptransfermessage',
            index=models.Index(fields=['status', '-created_at'], name='API_atomics_status_44c766_idx'),
        ),
    ]
