# Generated by Django 6.0.1 on 2026-08-07 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0008_alter_tradingpair_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='metadata_ipfs_cid',
            field=models.CharField(blank=True, default='', help_text='IPFS CID for standardized NFT metadata JSON', max_length=255),
        ),
        migrations.AddField(
            model_name='nft',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, help_text='Normalized NFT metadata payload'),
        ),
        migrations.AddField(
            model_name='nft',
            name='metadata_version',
            field=models.PositiveIntegerField(default=1, help_text='Version of the standardized NFT metadata schema'),
        ),
        migrations.CreateModel(
            name='UniqueAssetMintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_mode', models.CharField(choices=[('testnet', 'Testnet'), ('mainnet', 'Mainnet')], db_index=True, default='testnet', max_length=10)),
                ('admin_asset_symbol', models.CharField(max_length=255)),
                ('root_name', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(max_length=255)),
                ('unique_asset_name', models.CharField(max_length=255)),
                ('metadata_ipfs_cid', models.CharField(max_length=255)),
                ('metadata_version', models.PositiveIntegerField(default=1)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('mint_txid', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('broadcast', 'Broadcast'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_mint_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('network_mode', 'unique_asset_name'), name='unique_mint_request_network_asset_unique')],
            },
        ),
    ]
