# Generated by Django 6.0.1 on 2026-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0009_nft_metadata_ipfs_cid_nft_metadata_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueassetmintrequest',
            name='confirmation_depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniqueassetmintrequest',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueassetmintrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
