"""
Django settings for Tome project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import AutoConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
config = AutoConfig(search_path=str(PROJECT_ROOT))
MARKET_SYNC_ADDRESS = config('MARKET_SYNC_ADDRESS', default='EL5MFdaF8msRaUEDu9mxSNniPSswNmNRgq')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY', default='django-insecure-4lyj^1t98-fr9a_6uaw7=^+j60p5wzjgr*=&_!b&n@0vtc4pl$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='*').split(',')


# Application definition

INSTALLED_APPS = [
    'API',
    'DeFi',
    'Explorer',
    'Listings',
    'Media',
    'Settings',
    'User',
    'Wallet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'Settings.middleware.UserNetworkModeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Tome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Settings.context_processors.theme_context',
                'Wallet.context_processors.wallet_balance',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tome.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DEFAULT_FILE_STORAGE = 'ipfs_storage.InterPlanetaryFileSystemStorage'
IPFS_STORAGE_API_URL = config('IPFS_STORAGE_API_URL', default='http://localhost:5001/api/v0/')
IPFS_GATEWAY_API_URL = config('IPFS_GATEWAY_API_URL', default='http://localhost:8080/ipfs/')
IPFS_PUBLIC_GATEWAY_URLS = [
    url.strip()
    for url in config('IPFS_PUBLIC_GATEWAY_URLS', default='https://ipfs.io/ipfs/').split(',')
    if url.strip()
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Keep AutoField to match existing integer PKs
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Authentication settings
LOGIN_URL = '/user/login/'
AUTHENTICATION_BACKENDS = [
    'User.backends.EvrmoreWalletBackend',
    'django.contrib.auth.backends.ModelBackend',
]
EVRMORE_AUTH_DATABASE_PATH = config(
    'EVRMORE_AUTH_DATABASE_PATH',
    default=str(BASE_DIR / 'evrmore_auth.sqlite3'),
)
EVRMORE_AUTH_JWT_SECRET = config('EVRMORE_AUTH_JWT_SECRET', default=SECRET_KEY)
EVRMORE_AUTH_CHALLENGE_EXPIRY_MINUTES = config(
    'EVRMORE_AUTH_CHALLENGE_EXPIRY_MINUTES',
    default=10,
    cast=int,
)

# Email settings
# Using console backend for development - emails will be printed to console
# For production, change EMAIL_BACKEND to 'django.core.mail.backends.smtp.EmailBackend'
# and configure the settings below via environment variables
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')  # For development, prints emails to console
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@defitome.com')

# Evrmore RPC routing defaults
DEFAULT_EVRMORE_NETWORK = config('DEFAULT_EVRMORE_NETWORK', default=config('NETWORK', default='testnet'))
DEFAULT_EVRMORE_RPC_ENDPOINT_MODE = config('DEFAULT_EVRMORE_RPC_ENDPOINT_MODE', default='public')
RPC_DATADIR = config('RPC_DATADIR', default='/tmp/evrmore')
RPC_MAINNET_DATADIR = config('RPC_MAINNET_DATADIR', default=RPC_DATADIR)
RPC_TESTNET_DATADIR = config('RPC_TESTNET_DATADIR', default=RPC_DATADIR)

RPC_MAINNET_USER = config(
    'RPC_MAINNET_USER',
    default=config('MAINNET_RPC_USERNAME', default=config('RPC_USERNAME', default='')),
) or None
RPC_MAINNET_PASSWORD = config(
    'RPC_MAINNET_PASSWORD',
    default=config('MAINNET_RPC_PASSWORD', default=config('RPC_PASSWORD', default='')),
) or None
RPC_MAINNET_PORT = config(
    'MAINNET_RPC_PORT',
    default=config('RPC_MAINNET_PORT', default=config('RPC_PORT', default='')),
    cast=str,
) or None
RPC_MAINNET_HOST = config('RPC_MAINNET_HOST', default=config('RPC_HOST', default='')) or None
RPC_MAINNET_SCHEME = config('RPC_MAINNET_SCHEME', default='http')
RPC_MAINNET_PATH = config('RPC_MAINNET_PATH', default='/rpc')
RPC_MAINNET_URL = config('RPC_MAINNET_URL', default='') or None

RPC_TESTNET_USER = config(
    'RPC_TESTNET_USER',
    default=config('TESTNET_RPC_USERNAME', default=config('RPC_USERNAME', default='')),
) or None
RPC_TESTNET_PASSWORD = config(
    'RPC_TESTNET_PASSWORD',
    default=config('TESTNET_RPC_PASSWORD', default=config('RPC_PASSWORD', default='')),
) or None
RPC_TESTNET_PORT = config(
    'TESTNET_RPC_PORT',
    default=config('RPC_TESTNET_PORT', default=config('RPC_PORT', default='')),
    cast=str,
) or None
RPC_TESTNET_HOST = config('RPC_TESTNET_HOST', default=config('RPC_HOST', default='')) or None
RPC_TESTNET_SCHEME = config('RPC_TESTNET_SCHEME', default='http')
RPC_TESTNET_PATH = config('RPC_TESTNET_PATH', default='/rpc')
RPC_TESTNET_URL = config('RPC_TESTNET_URL', default='') or None

RPC_TIMEOUT_SECONDS = config('RPC_TIMEOUT_SECONDS', default=10, cast=int)
RPC_PUBLIC_TIMEOUT_SECONDS = config('RPC_PUBLIC_TIMEOUT_SECONDS', default=10, cast=int)

EVRMORE_PUBLIC_RPC_MAINNET_URL = config(
    'EVRMORE_PUBLIC_RPC_MAINNET_URL',
    default='https://evr-rpc-mainnet.evrmorecoin.org/rpc',
)
EVRMORE_PUBLIC_RPC_TESTNET_URL = config(
    'EVRMORE_PUBLIC_RPC_TESTNET_URL',
    default='https://evr-rpc-testnet.evrmorecoin.org/rpc',
)

# DEC casino routing for instance fees and game-spend settlements.
DEC_SYSTEM_FEE_ADDRESS = config('DEC_SYSTEM_FEE_ADDRESS', default='')
DEC_SYSTEM_FEE_ADDRESS_MAINNET = config('DEC_SYSTEM_FEE_ADDRESS_MAINNET', default='')
DEC_SYSTEM_FEE_ADDRESS_TESTNET = config('DEC_SYSTEM_FEE_ADDRESS_TESTNET', default='')
DEC_PLAYER_WAGER_TREASURY_BPS = config('DEC_PLAYER_WAGER_TREASURY_BPS', default=5000, cast=int)

