# Generated by Django 6.0.1 on 2026-08-07 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeFi', '0007_swapoffer_network_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swapoffer',
            name='settlement_temp_txid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SwapFundingLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('released', 'Released'), ('consumed', 'Consumed')], db_index=True, default='locked', max_length=10)),
                ('lock_reason', models.CharField(default='atomic_swap_settlement', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('swap_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_locks', to='DeFi.swapoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_funding_locks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
