# Generated by Django 6.0.1 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_addressmetadatatag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipfsupload',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
